Make parallel jobs

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -81,13 +81,14 @@ jobs:
     needs: [symfony-initial, nodejs-initial]
     runs-on: ubuntu-latest
     steps:
-    - name: Run Migration
-      run: |
-        php bin/console --env=test doctrine:migrations:migrate || echo "No migrations found or migration failed"
-        php bin/console doctrine:fixtures:load --env=test --append
-      env:
-        DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/app?charset=utf8
-    - name: Execute tests (Unit and Feature tests) via PHPUnit
-      env:
-        DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/app?charset=utf8
-      run: ./vendor/bin/phpunit
+      - uses: actions/checkout@v2
+      - name: Run Migration
+        run: |
+          php bin/console --env=test doctrine:migrations:migrate || echo "No migrations found or migration failed"
+          php bin/console doctrine:fixtures:load --env=test --append
+        env:
+          DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/app?charset=utf8
+      - name: Execute tests (Unit and Feature tests) via PHPUnit
+        env:
+          DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/app?charset=utf8
+        run: ./vendor/bin/phpunit
