Make parallel jobs

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -82,13 +82,15 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
+      - name: Install Dependencies
+        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
       - name: Run Migration
         run: |
-          php ${{ github.workspace }}/bin/console --env=test doctrine:migrations:migrate || echo "No migrations found or migration failed"
-          php ${{ github.workspace }}/bin/console doctrine:fixtures:load --env=test --append
+          php bin/console --env=test doctrine:migrations:migrate || echo "No migrations found or migration failed"
+          php bin/console doctrine:fixtures:load --env=test --append
         env:
           DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/app?charset=utf8
       - name: Execute tests (Unit and Feature tests) via PHPUnit
         env:
           DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/app?charset=utf8
-        run: ${{ github.workspace }}/vendor/bin/phpunit
+        run: ./vendor/bin/phpunit
