Add cs fixer, phpstan

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -50,7 +50,7 @@ jobs:
     - name: Run php-cs-fixer
       run: ./tools/php-cs-fixer/vendor/bin/php-cs-fixer fix ./src/ --dry-run --rules=@PSR12 --diff 
     - name: Run Migration
-      run: php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+      run: php bin/console --env=test doctrine:migrations:migrate || echo "No migrations found or migration failed"
       env:
         DATABASE_URL: postgresql://symfony:symfony@127.0.0.1:5432/app_test?charset=utf8
     - name: Execute tests (Unit and Feature tests) via PHPUnit
