Add cs fixer, phpstan

diff --git a/.github/workflows/symfony.yml b/.github/workflows/symfony.yml
--- a/.github/workflows/symfony.yml
+++ b/.github/workflows/symfony.yml
@@ -38,6 +38,8 @@ jobs:
       run: |
         mkdir -p data
         touch data/database.sqlite
+    - name: Run Migration
+      run: php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
     - name: Execute tests (Unit and Feature tests) via PHPUnit
       env:
         DATABASE_URL: sqlite:///%kernel.project_dir%/data/database.sqlite
